apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment-v
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat-app
  template:
    metadata:
      labels:
        app: tomcat-app
    spec:
      containers:
      - name: java-app-vikas
        image: vikaskarbail/java-app-vikas:latest
        ports:
        - containerPort: 8080
