# apiVersion: v1 
# kind: Service
# metadata:
#   name: java-service-v
# spec:
#   type: NodePort
#   ports:
#     - port: 80
#       targetPort: 8080
#       nodePort: 30008
#       protocol: TCP
#   selector:
#     app: tomcat-app

apiVersion: v1
kind: Service
metadata:
  name: java-service-v
spec:
  type: NodePort
  selector:
    app: tomcat-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30008  

